### ISSUE TITLE
ping error

### ISSUE THREAD

**Issue by caoyanglee** [flymzero/webdav_client#19]
自己搭建的Cloudreve。

完整请求日志
```bash
*** Request ***
uri: https://p4.cdsjcc.cn/dav/
method: OPTIONS
responseType: ResponseType.json
followRedirects: false
connectTimeout: 800000
sendTimeout: 800000
receiveTimeout: 800000
receiveDataWhenStatusError: true
extra: {}
headers:
 accept-charset: utf-8
 depth: 0

*** DioError ***:
uri: https://p4.cdsjcc.cn/dav/
DioError [DioErrorType.other]: SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = p4.cdsjcc.cn, port = 55968

```

**Comment by flymzero** [comment]
@caoyanglee  我测试了Cloudreve的[在线演示地址](https://demo.cloudreve.org/home?path=%2F)，一切ok

你可以新建个账号试试，修改我单元测试**webdav_client_test.dart**的地址，账号，密码进行测试

木问题的请关闭issue

**以下是我ping的输出**
 ```
sendTimeout: 8000
receiveTimeout: 8000
receiveDataWhenStatusError: true
extra: {}
headers:
 accept-charset: utf-8
 depth: 0

*** Response ***
uri: https://demo.cloudreve.org/dav/
statusCode: 200
headers:
 connection: keep-alive
 dav: 1, 2
 date: Fri, 19 Aug 2022 16:28:37 GMT
 content-encoding: gzip
 vary: Accept-Encoding
 cf-cache-status: DYNAMIC
 report-to: xxxxx
 expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
 ms-author-via: DAV
 server: cloudflare
 alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
 content-length: 23
 nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
 cf-ray: 73d443690fe4c4d9-SEA
 allow: OPTIONS, LOCK, PUT, MKCOL
Response Text:
2

✓ common settings
```

**以下是make folder的输出**
```
receiveTimeout: 0
receiveDataWhenStatusError: true
extra: {}
headers:
 authorization: Basic xxxxx

*** Response ***
uri: https://demo.cloudreve.org/dav/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9/
statusCode: 201
headers:
 connection: keep-alive
 alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
 date: Fri, 19 Aug 2022 16:31:31 GMT
 content-encoding: gzip
 vary: Accept-Encoding
 content-length: 31
 nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
 cf-ray: 73d447aec9fcc711-SEA
 report-to: xxxx
 cf-cache-status: DYNAMIC
 expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
 server: cloudflare
Response Text:
Created

✓ make folder
```
